Mojave-Sun/mojave-sun

_maps/map_files/Mammoth/Mammoth.dmm
code/_onclick/hud/plane_master.dm
code/modules/lighting/sunlight_object.dm

there are probably bugs but it seems hunky doory
I have replaced all openspace turfs in the map with the new transparent ones

Update sunlight to use new procs

---

_maps/map_files/Mammoth/Mammoth.dmm

Made the police station bigger and better. Its non-shit anymore. I actually kind of hate everything I've done so far so I might redo everything. Maybe not. Probably not.
Main floor. Has everything you need to be epic. ! 2 armor spawns, 2 gun spawns, 3 ammo spawns in the armory, all tier 1. One (1) tier two (2) armor spawn in the boss' room. Also some donk pockets.
Basement. Has prisoner things and also a storage room. One of the cells leads into the caves. One tier 1 gun spawn and a costume spawner in the storage room.
The last one was bad. This one isn't.

Police station remake

---

_maps/combatarena.json
_maps/mammoth.json
_maps/map_files/CombatArena/CombatArena.dmm
code/game/turfs/open/openspace.dm
fallout/turfs/plating.dm

Fixed a few openspace turfs references being incorrect.  They now reference the newer transparent openspace turf.
Stops turf deletion from making an erroneous turf.

Fix openspace

---

code/controllers/subsystem/sunlight.dm
code/game/turfs/change_turf.dm
code/modules/lighting/sunlight_object.dm

Fix funky sunlight issues from
multi-z changes
construction
explosions
I have probably buggered something or missed something, let me know xo

Fix funky new quirks + improve indoor checks

---

tgstation.dme

DM has a bad tendency to remove includes in the dme
DM is bad.

Include was removed from last PR.

---

_maps/map_files/Mammoth/Mammoth.dmm

Reverts due to the PR being built on an outdated version of the map.

Revert "Third Attempt to PR this Rework"

---

_maps/map_files/Mammoth/Mammoth.dmm

Mammoth just got a little bit more detailed. Adds two new buildings: Mammoth Town Hall and Post Office, and the Tipsy Mogul raider bar. Each is packed with detail, environmental storytelling, and enough placeholders to make a spriter cry.
The Tipsy Mogul, as occupied by our resident raider gang (Live music on Saturdays, happy hour from 7 to 8):
Town Hall, where the fine folks of Mammoth attend community meetings, send mail, and write messages for everyone to see:
Town Hall's upper floor, with the archives and mayor's office, please take a ticket and you'll be out of here real quick:
And finally, the mail sorting room:
Mammoth takes one more step towards completion.

Mammoth Map MStuff, part 2: Raiders Did A Bad

---

config/game_options.txt

Lowers the speed delay from running and walking by .05 each. 
2.25 and 4 down to 2.20 and 3.95 respectively.
Makes the movement speed just-right, IMO. Its quick but not stupid-fast.

Movement speed change

---

code/__DEFINES/icon_smoothing.dm
code/__HELPERS/icon_smoothing.dm
code/datums/elements/embed.dm
code/game/atoms.dm
code/game/turfs/turf.dm
code/modules/lighting/lighting_atom.dm
code/modules/lighting/lighting_turf.dm
code/modules/lighting/sunlight_object.dm
fallout/items/hay_stack.dm
fallout/items/weaponry.dm
fallout/machinery/console_puzzles.dm
fallout/structures/table.dm
fallout/turfs/low_wall.dm
fallout/turfs/minerals.dm
fallout/turfs/wall.dm
fallout/turfs/window.dm

I have wrecked icon_smoothing. its still a todo
also this is untested

This is more compiley than ever before

---

.git-blame-ignore-revs

Following up on https://github.com/Mojave-Sun/mojave-sun/pull/97
Why ISN'T it good for the game?

Gitignore for huge line ending PR.

---

_maps/map_files/Mammoth/Mammoth.dmm

This adds a hat store to a small currently empty building in Mammoth.
This PR also fixes some space turfs being on the map nearby.
Hats are fun, space tiles are not.

Hat store, and space tile fix.

---

_maps/map_files/Mammoth/Mammoth.dmm

Yet another PR trying to appease Travis.

Remove fire extinguisher cabinet with pixel-z offset from Mammoth.

---

_maps/map_files/Mammoth/Mammoth.dmm
fallout/effects/spawners/corpse.dm
tgstation.dme

Due to job code, using the assistant corpse spawner was generating a runtime.
We need to make our own corpse spawners anyway, here's a start.

Fixes corpse runtime on Mammoth, creates /f13 corpses.

---

_maps/map_files/Mammoth/Mammoth.dmm

Adds changes to Mammoth.dmm
This PR adds two newly finished building interiors to the downtown/main portion of the Mammoth map.
This includes a hip burger joint, the scene of many a sockhop in days of old, only to close due to an untimely accident, and a solo practicing lawyer's office where the aspiring law official met an untimely end shortly before the world itself changed forever.
These two buildings were previously completely empty. These changes fix that and add just a little more flavor to the game world.

Adds map changes

---

_maps/map_files/Mammoth/Mammoth.dmm

Adds wooden floors under half-walls where there was originally space tiles. My bad!
Open holes to space are not good for the game.
before
after

Fixes the floor.

---

_maps/map_files/Mammoth/Mammoth.dmm

I went through, adding a shitton of lights to buildings that lacked them, as well as fixing the NCR's carpet, as it was a holodeck carpet instead of ours. Two new buildings were added, sitting on the top Z level that look pretty okay. 
Finished messing around with the facility entrance dungeon.
The raider boys have a second story with a bit more in it, All spawners for the raiders put in properly this time.
Along with that, I've carved out a piece of mountain on the top-most Z-level near the BOS and Interior town

Random map fixes, changes, and two new buildings.

---

code/__DEFINES/icon_smoothing.dm
fallout/__DEFINES/icon_smoothing.dm
tgstation.dme

Moves the MS smoothing groups to its own file

---

code/__DEFINES/tgs.dm
code/modules/tgs/v3210/api.dm
code/modules/tgs/v3210/commands.dm
code/modules/tgs/v5/api.dm

Automated update for TGS.
update gud

Update TGS DMAPI

---

code/__DEFINES/tgs.dm
code/modules/tgs/v3210/api.dm
code/modules/tgs/v3210/commands.dm
code/modules/tgs/v5/api.dm

Reverts Mojave-Sun/mojave-sun#143
Think I may have done the action's job for it accidently.

Revert "Update TGS DMAPI"

---

fallout/items/devices/radio/radiopack.dm

Adds radio packs, and at some point i will also have radio channels for each faction
Adding radiopacks gives you a way to communicate without giving everyone radios, encouraging teamwork

Adds Radiopacks

---

fallout/tools/merge-upstream-pull-request.sh

Adds shell script for PRMirror bot.
See above

Adds needed files for PR bot

---

merge-upstream-pull-request.sh

Changes the shell script for the merge bot to the austation version.
austation's merge bot should be a bit more robust for our needs.

Changes to merge bot script

---

_maps/map_files/Mammoth/Mammoth.dmm

The layout of the NCR camp on mammoth seemed a bit strange so I took a bit of time to change it up a bit. The biggest change was moving the prison area to underneath the medical building. An administration-type building was put in it's place. The rest were fairly minor changes, but my grasp on the balance of this map isn't great. If things could be looked over, it would be much appreciated. That's also why I haven't added much and more just rearranged things to look nicer.
Here are some pictures: 
It makes sense that the prison would be moved underground, and leaves the precious surface space to more important things. This is just something quick I messed with to try and get more familiar with the maps and sprites and such, but I thought it would work well if added, so I decided to pr it.

Rearranging the NCR Camp on Mammoth

---

mojave/items/clothing/head/helmet.dm
mojave/items/clothing/suits/armor.dm
mojave/items/guns/ballistic.dm
mojave/items/guns/projectiles/pistol-proj.dm
mojave/items/guns/projectiles/revolver-proj.dm
mojave/items/guns/projectiles/rifle-proj.dm
mojave/items/guns/weapons/automatic.dm
mojave/items/guns/weapons/pistol.dm
mojave/items/guns/weapons/revolver.dm
mojave/items/guns/weapons/rifle.dm
mojave/items/guns/weapons/shotgun.dm

Wounds are now implemented for guns and are somewhat balanced. Capitalization fixes, minor adjustments to heavy armor slowdown that was suggested, and proper melee force for guns. 
Wounds are literally amazing.

Wounds and other wounds

---

tools/WebhookProcessor/github_webhook_processor.php

https://github.com/tgstation/tgstation/pull/55546
Might make CI work again

Ports changes from tgstation for php webhooks

---

_maps/map_files/Mammoth/Mammoth.dmm
mojave/structures/decorative.dm

This PR replaces the NCR's currently lackluster base. It gives them a much more eye-catching location. Try to take a guess on what it is- Go ahead.... I don't know if I could but it's inspired by a little snowy resort type of place, and I hope that's at least somewhat evident in it. I'm actively working on this so i'll keep this as a draft for now. But hopefully this can breathe some necessary life into the NCR's existence and give them some buildings to use with more of a past to them. 
The Staff Sergeant even has his personal neckbeard nest next to the underground armory based behind the resort's front desk which he will often man, acting as a quartermaster.
Gives the NCR a quirky base, better than three squares. Would be really cool and helps people notice the NCR. The larger scale …

NCR base redux- Resort edition

---

_maps/map_files/Mammoth/Mammoth.dmm

Adds some detail to the police station's garage. It was previously empty and only had roads inside of it. Also populates the second Chopshop with furniture.
Empty buildings were empty, now they're not. 
The shutters work, but are normally unpowered. At least for now they are.

Police station garage fix and Chopshop

---

_maps/map_files/Mammoth/Mammoth.dmm

PLEASE GOD SMITE THE GHOULS THAT CREATED THIS HORRID APPLICATION

GITHUB SUCKS PART 4

---

mojave/mob/ms13mobs.dm

Makes the fallout simple animals actually be able to be deleted
So you can't just for example infinitely butcher a molerat

You can now delete the fallout simple mobs

---

mojave/code/datums/components/thirst.dm

You get notified less about being thirsty
Above

Makes the human mob less thirsty

---

mojave/code/datums/components/thirst.dm

Makes thirst less likely to break from var edits and actually introduces good benchmarks
See above i guess

Thirst slight refactor and bit more varedit friendly

---

_maps/map_files/Mammoth/Mammoth.dmm

Shit. Fuck. Looks like you win this round, @ProfessorPopoff.
Anyway, adds the Vault Town to the map. It's kinda rough around the edges right now, a lot of placeholders and such, but it can be refined as we get more assets- and, you know, it actually sorts out a base for one of our major factions.
I know this is gonna have issues, so reviews are welcomed.
Town is a big faction, right? If town is a big faction, it needs a base.

Adds the Vault Town to Mammoth

---

_maps/map_files/Mammoth/Mammoth.dmm

Makes some changes to the NCR base. Everything is mostly the same from #271 but isn't broken, look there for a detailed description. :)
Makes the NCR base homely. :)

NCR base tweaks. :)

---

_maps/map_files/Mammoth/Mammoth.dmm

As the title says. Apparently Riddler scuffed a push last second as I went to merge his PR, and thus the areas and kinda screwed up over here. As seen in the screenshots, they're fixed. Nothing else has been touched by this PR.

Fixes Riddler's oopsie

---

_maps/map_files/Mammoth/Mammoth.dmm

Maaany changes. Police Station, Hotel, Library, Gym, Old Town Hall, some stores, bars etc.
I attached some screenshots, but mainly of first floors. Of course, some buildings has second floors and basement, but there are "roof helpers" on it, so there's no need to attach them too. You'll understand which buildings has second floor, and which are not.
UPDATE 1:
UPDATE 2:
UPDATE 3:
Fixed that.
UPDATE 4:
This basement.

Map Overhaul from Riddler, part 1

---

_maps/map_files/Mammoth/Mammoth.dmm

Removed old bunker in a mountain. Replaced it with Powerplant (with Administration and Canteen). Improved Underground Village.
Made a Warehouse and Robotics Shop near Powerplant. Replaced and improved two buildings that were on their place before.
Reworked some "maintenance room" in a Sewers nearby Village that I made before. Fixed a stairs.
Fixed one  unnecessary "roof helper" on a Police Station (spotted it in a last time when I opened the map).

Going Nuclear: Powerplant and Village

---

_maps/map_files/Mammoth/Mammoth.dmm

Updated a Mountain Complex, reworked it into Military Communication Outpost with warehouses, lift, engineering rooms, data rooms, small medical post, ruined canteen etc.

Roger That: Military Communication Outpost

---

mojave/code/datums/components/thirst.dm

Makes dying from lack of water give a bit more time until death
Someone requested it

Water but less lethal

---

_maps/map_files/Mammoth/Mammoth.dmm

Added a fancy Infra's safes and wall-mounted aid kits all over the map. Aid kits can be found generally in a toilets.
Also added a fancy cables - tiles and objects, generally in Powerplant. Oh yeah, and rubber rugs!
And a small little addition - remade one shop into Warehouse, added a local "gasoline station" (probably coolant, just call it "Local Red Rocket") and made a little bunker underground. And yeah, fixed a basement of Hotel. 
P.S. Real movavi moment.

Safety first: Safes, First Aid Kits and other

---

_maps/map_files/Mammoth/Mammoth.dmm

Remade entire Gym (call it Iron Muscles I dunno) nearby Hotel.
Remade a Pharmacy (dunno, Hillington's Pharmacy?) and ruined building nearby.

Mammoth Healthcare, part 1: Gym and Pharmacy Shop.

---

_maps/map_files/Drought/Drought.dmm

Did changes to the cult compound in the northwest of the map, and the shooting range directly east of it
Moved the gibber in the town's butcher shop at the southeast intersection
Turned the weird building in the middle of the town into some kind of weird store(that doesn't look like amogus FUCK YOU WHYMAN)
Replaced a misused varedit wood tile on the building directly southwest of the Legion base(and also added lights(realized that was my mistake oops))
Did a bit of T&L on the 5 houses on the northwest of the town, from adding/removing a few things to completely redoing/completing the layout and moving the whole building in one case
Removed a door under a low wall in the house east of those 5 houses

Drought map changes for to of before port map; the changes
